version: '3.4'
services:

  db:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TechValleyDotNetUserGroup!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - e:/T/TVUG/SharedVolume:/var/opt/mssql
    networks:
      mynetwork:
        aliases:
          - aspcoredb

  web: 
    build:
      context: ./
      dockerfile: dev.dockerfile
    user: root
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8080:5432"
    networks:
      mynetwork:
        aliases:
          - web1.internal.prod.example.com

networks:
  mynetwork:
    driver: bridge

    